"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { aboutMe } from "@/lib/portfolio-data";
import { Button } from "@/components/ui/button";
import { getResumeSummary } from "@/app/actions";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { Loader2 } from "lucide-react";

export function AboutSection() {
  const [isPending, startTransition] = useTransition();
  const [summary, setSummary] = useState<string | null>(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const { toast } = useToast();

  const handleGenerateSummary = () => {
    setIsDialogOpen(true);
    if (summary) return; // Don't re-generate if we already have it

    startTransition(async () => {
      const result = await getResumeSummary();
      if ("summary" in result) {
        setSummary(result.summary);
      } else {
        toast({
          variant: "destructive",
          title: "Error",
          description: result.error,
        });
        setIsDialogOpen(false);
      }
    });
  };

  return (
    <section id="about" className="container">
      <div className="grid grid-cols-1 items-center gap-12">
        <div className="space-y-6 text-center">
          <h2 className="font-headline text-3xl font-bold tracking-tight sm:text-4xl">
            About Me
          </h2>
          <p className="mx-auto max-w-3xl text-lg text-muted-foreground">
            A passionate and disciplined individual with a deep-rooted love for <Link href="#project-rental-car" className="text-primary underline">data analysis</Link>, <Link href="#project-microgt-services" className="text-primary underline">automation</Link>, and digital systems. My journey is guided by the values of continuous learning, unwavering commitment, and a respect for tradition, which I blend with a forward-thinking approach to technology. I thrive on uncovering insights from data and building efficient systems that drive innovation.
          </p>
          <div className="flex items-center justify-center gap-4 pt-4">
             <Button onClick={handleGenerateSummary}>Generate AI Resume Summary</Button>
          </div>
        </div>
      </div>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>AI-Generated Resume Summary</DialogTitle>
            <DialogDescription>
              A concise summary of Omkar's profile, generated by AI.
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            {isPending ? (
              <div className="flex items-center justify-center space-x-2">
                <Loader2 className="h-6 w-6 animate-spin text-primary" />
                <p>Generating summary...</p>
              </div>
            ) : (
              <p className="text-sm text-foreground">{summary}</p>
            )}
          </div>
          <DialogFooter>
            <Button onClick={() => setIsDialogOpen(false)}>Close</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </section>
  );
}
